// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:convert';
import 'dart:typed_data';

import '../../contracts/codable.dart';
import '../../contracts/decoder.dart';
import '../../contracts/encoder.dart';
import '../../contracts/exceptions.dart';
import '../../contracts/static_key.dart';
// Generated by: dart run tool/switch_substrate.dart <mock|native>
import '../substrate/substrate.dart';
import 'adaptive_writer.dart';
import 'scratch_byte_accumulator.dart';

/// Concrete high-performance driver connecting `package:codable` contracts
/// directly to `JsonTokenReader` and `JsonTokenWriter`.
final class JsonCodableDecoder implements Decoder {
  final JsonTokenReader _reader;
  final Uint8List? _bytes;
  bool _payloadEscaped = false;

  @override
  final Map<Object, Object?> userInfo;

  /// Exposes the underlying pull-based token reader for direct, devirtualized
  /// decoding.
  JsonTokenReader get reader {
    _payloadEscaped = true;
    return _reader;
  }

  @override
  Uint8List? get payload {
    _payloadEscaped = true;
    return _bytes ?? _reader.bytes;
  }

  JsonCodableDecoder.fromReader(this._reader, {this.userInfo = const {}})
    : _bytes = null;

  factory JsonCodableDecoder.fromBytes(
    Uint8List bytes, {
    Map<Object, Object?> userInfo = const {},
  }) {
    return JsonCodableDecoder._(
      JsonTokenReader.fromBytes(bytes),
      bytes,
      userInfo: userInfo,
    );
  }

  factory JsonCodableDecoder.fromString(
    String source, {
    Map<Object, Object?> userInfo = const {},
  }) {
    final bytes = Uint8List.fromList(utf8.encode(source));
    return JsonCodableDecoder.fromBytes(bytes, userInfo: userInfo);
  }

  /// Starts a chunked conversion that accumulates incoming UTF-8 byte chunks
  /// and invokes [decodable] on the resulting [JsonCodableDecoder] when closed,
  /// emitting the decoded value to [sink].
  static ByteConversionSink startChunkedConversion<T>(
    Sink<T> sink,
    Decodable<T> decodable, {
    Map<Object, Object?> userInfo = const {},
  }) {
    return _JsonCodableChunkedDecoderSink<T>(sink, decodable, userInfo);
  }

  JsonCodableDecoder._(this._reader, this._bytes, {this.userInfo = const {}});

  @override
  KeyedDecoder keyed({KeyOptions? options}) =>
      _JsonCodableKeyedDecoder(_reader, this, options: options);

  @override
  MappedDecoder mapped() => createMappedDecoderFromReader(_reader, userInfo);

  @override
  UnkeyedDecoder unkeyed() => _JsonCodableUnkeyedDecoder(_reader, this);

  @override
  SingleValueDecoder singleValue() =>
      _JsonCodableSingleValueDecoder(_reader, this);

  @override
  Float64List? decodeUniformDoubleList(List<List<String>> propertyAliases) =>
      decodeUniformDoubleListFromReader(_reader, propertyAliases);
}

final _uniformKeyOptionsCache =
    Expando<({JsonKeyOptions options, Int32List fieldMap})>();

({JsonKeyOptions options, Int32List fieldMap}) _compileUniformAliases(
  List<List<String>> propertyAliases,
) {
  final cached = _uniformKeyOptionsCache[propertyAliases];
  if (cached != null) return cached;
  final flatKeys = <String>[];
  final mapList = <int>[];
  for (var fieldIdx = 0; fieldIdx < propertyAliases.length; fieldIdx++) {
    for (final alias in propertyAliases[fieldIdx]) {
      flatKeys.add(alias);
      mapList.add(fieldIdx);
    }
  }
  final built = (
    options: JsonKeyOptions.of(flatKeys),
    fieldMap: Int32List.fromList(mapList),
  );
  try {
    _uniformKeyOptionsCache[propertyAliases] = built;
  } on Object {
    // Ignore if propertyAliases cannot be attached to Expando.
  }
  return built;
}

/// Decodes a uniform array of numeric objects directly from [reader] into a
/// flat [Float64List] without per-element [KeyedDecoder] allocations.
Float64List? decodeUniformDoubleListFromReader(
  JsonTokenReader reader,
  List<List<String>> propertyAliases,
) {
  final kCount = propertyAliases.length;
  if (kCount == 0 || kCount > 30) return null;
  final compiled = _compileUniformAliases(propertyAliases);
  final options = compiled.options;
  final fieldMap = compiled.fieldMap;
  final expectedMask = (1 << kCount) - 1;

  try {
    reader.beginArray();
    var estimatedRows = (reader.bytes.length ~/ (10 * kCount + 8)).clamp(
      256,
      16384,
    );
    var out = Float64List(estimatedRows * kCount);
    var outLen = 0;
    final row = Float64List(kCount);

    while (reader.moveNext()) {
      reader.beginObject();
      var seenMask = 0;
      while (reader.moveNext()) {
        final keyIdx = reader.selectName(options);
        if (keyIdx < 0) {
          reader.skipValue();
        } else {
          final fieldIdx = fieldMap[keyIdx];
          final bit = 1 << fieldIdx;
          if ((seenMask & bit) != 0) {
            throw CodableException(
              'Duplicate field "${propertyAliases[fieldIdx].first}"',
            );
          }
          row[fieldIdx] = reader.readDouble();
          seenMask |= bit;
        }
      }
      if (seenMask != expectedMask) {
        final missing = <String>[];
        for (var k = 0; k < kCount; k++) {
          if ((seenMask & (1 << k)) == 0) {
            missing.add(propertyAliases[k].first);
          }
        }
        throw CodableException(
          'Missing required fields: ${missing.join(", ")}',
        );
      }
      reader.endObject();

      if (outLen + kCount > out.length) {
        final next = Float64List(out.length * 2);
        next.setRange(0, outLen, out);
        out = next;
      }
      for (var k = 0; k < kCount; k++) {
        out[outLen++] = row[k];
      }
    }
    reader.endArray();
    if (outLen == out.length) return out;
    if (out.length - outLen <= 512 || outLen >= (out.length >> 2)) {
      return Float64List.sublistView(out, 0, outLen);
    }
    return out.sublist(0, outLen);
  } on CodableException {
    rethrow;
  } on Object catch (e) {
    throw CodableException('Failed to decode uniform double list: $e');
  }
}

mixin _JsonPrimitiveDecoderMixin {
  JsonTokenReader get _reader;
  void _ensureStarted();

  @pragma('vm:prefer-inline')
  bool isNextNull() {
    _ensureStarted();
    return _reader.peek() == JsonTokenType.nullValue;
  }

  @pragma('vm:prefer-inline')
  void readNull() {
    _ensureStarted();
    _reader.readNull();
  }

  @pragma('vm:prefer-inline')
  int readInt() {
    _ensureStarted();
    return _reader.readInt();
  }

  @pragma('vm:prefer-inline')
  int? readNullableInt() {
    _ensureStarted();
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readInt();
  }

  @pragma('vm:prefer-inline')
  double readDouble() {
    _ensureStarted();
    return _reader.readDouble();
  }

  @pragma('vm:prefer-inline')
  double? readNullableDouble() {
    _ensureStarted();
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readDouble();
  }

  @pragma('vm:prefer-inline')
  String readString() {
    _ensureStarted();
    return _reader.readString();
  }

  @pragma('vm:prefer-inline')
  String? readNullableString() {
    _ensureStarted();
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readString();
  }

  @pragma('vm:prefer-inline')
  (int start, int end) readStringSpan() {
    _ensureStarted();
    return _reader.readStringSpan();
  }

  @pragma('vm:prefer-inline')
  (int start, int end)? readNullableStringSpan() {
    _ensureStarted();
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readStringSpan();
  }

  @pragma('vm:prefer-inline')
  bool readBool() {
    _ensureStarted();
    return _reader.readBool();
  }

  @pragma('vm:prefer-inline')
  bool? readNullableBool() {
    _ensureStarted();
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readBool();
  }
}

final class _JsonCodableKeyedDecoder
    with _JsonPrimitiveDecoderMixin
    implements KeyedDecoder {
  @override
  final JsonTokenReader _reader;
  final JsonCodableDecoder _rootDecoder;
  final KeyOptions? _options;
  final JsonKeyOptions? _compiledOptions;
  bool _started = false;
  bool _ended = false;

  _JsonCodableKeyedDecoder(
    this._reader,
    this._rootDecoder, {
    KeyOptions? options,
  }) : _options = options,
       _compiledOptions = options != null
           ? ((options.compiled ??= JsonKeyOptions.of(options.keys))
                 as JsonKeyOptions)
           : null;

  @override
  @pragma('vm:prefer-inline')
  void _ensureStarted() {
    if (!_started) {
      _reader.beginObject();
      _started = true;
    }
  }

  @override
  @pragma('vm:prefer-inline')
  bool moveNextKey() {
    if (_ended) return false;
    _ensureStarted();
    final has = _reader.moveNext();
    if (!has) {
      _reader.endObject();
      _ended = true;
    }
    return has;
  }

  @override
  @pragma('vm:prefer-inline')
  String nextKey() {
    _ensureStarted();
    return _reader.nextName();
  }

  @override
  String? peekKey() {
    _ensureStarted();
    return null;
  }

  @override
  @pragma('vm:prefer-inline')
  int selectKeyIndex(KeyOptions options) {
    _ensureStarted();
    final compiled = identical(options, _options)
        ? _compiledOptions!
        : ((options.compiled ??= JsonKeyOptions.of(options.keys))
              as JsonKeyOptions);
    return _reader.selectName(compiled);
  }

  @override
  int selectStringIndex(KeyOptions options) {
    _ensureStarted();
    final compiled = identical(options, _options)
        ? _compiledOptions!
        : ((options.compiled ??= JsonKeyOptions.of(options.keys))
              as JsonKeyOptions);
    return _reader.selectString(compiled);
  }

  @override
  void skipValue() {
    _ensureStarted();
    _reader.skipValue();
  }

  @override
  @pragma('vm:prefer-inline')
  Decoder nestedDecoder() => _rootDecoder;

  @override
  @pragma('vm:prefer-inline')
  T decodeValue<T>(Decodable<T> decodable) => decodable.decode(_rootDecoder);

  @override
  @pragma('vm:prefer-inline')
  T? decodeNullableValue<T>(Decodable<T> decodable) {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return decodeValue(decodable);
  }

  @override
  List<T> decodeList<T>(Decodable<T> decodable) {
    _ensureStarted();
    final list = <T>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(decodable.decode(_rootDecoder));
    }
    _reader.endArray();
    return list;
  }

  @override
  List<T>? decodeNullableList<T>(Decodable<T> decodable) {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return decodeList(decodable);
  }

  @override
  List<int> decodeIntList() {
    _ensureStarted();
    final list = <int>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readInt());
    }
    _reader.endArray();
    return list;
  }

  @override
  List<double> decodeDoubleList() {
    _ensureStarted();
    final list = <double>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readDouble());
    }
    _reader.endArray();
    return list;
  }

  @override
  Float64List decodeFloat64List() {
    _ensureStarted();
    final list = <double>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readDouble());
    }
    _reader.endArray();
    return Float64List.fromList(list);
  }

  @override
  List<String> decodeStringList() {
    _ensureStarted();
    final list = <String>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readString());
    }
    _reader.endArray();
    return list;
  }

  @override
  List<bool> decodeBoolList() {
    _ensureStarted();
    final list = <bool>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readBool());
    }
    _reader.endArray();
    return list;
  }
}

/// Parses a JSON object from [reader] into a random-access [MappedDecoder]
/// backed by an in-memory object tree without re-serializing nested values.
MappedDecoder createMappedDecoderFromReader(
  JsonTokenReader reader,
  Map<Object, Object?> userInfo,
) {
  return _DartObjectMappedDecoder(_readObjectFromReader(reader), userInfo);
}

Map<String, Object?> _readObjectFromReader(JsonTokenReader reader) {
  reader.beginObject();
  final map = <String, Object?>{};
  while (reader.moveNext()) {
    final key = reader.nextName();
    map[key] = _readValueFromReader(reader);
  }
  reader.endObject();
  return map;
}

Object? _readValueFromReader(JsonTokenReader reader) {
  final type = reader.peek();
  switch (type) {
    case JsonTokenType.nullValue:
      reader.readNull();
      return null;
    case JsonTokenType.boolean:
      return reader.readBool();
    case JsonTokenType.number:
      return reader.readNum();
    case JsonTokenType.string:
      return reader.readString();
    case JsonTokenType.beginObject:
      return _readObjectFromReader(reader);
    case JsonTokenType.beginArray:
      reader.beginArray();
      final list = <Object?>[];
      while (reader.moveNext()) {
        list.add(_readValueFromReader(reader));
      }
      reader.endArray();
      return list;
    default:
      reader.skipValue();
      return null;
  }
}

final class _DartObjectDecoder implements Decoder {
  final Object? _value;
  @override
  final Map<Object, Object?> userInfo;

  _DartObjectDecoder(this._value, {this.userInfo = const {}});

  @override
  Uint8List? get payload => null;

  @override
  KeyedDecoder keyed({KeyOptions? options}) {
    final v = _value;
    if (v is Map<String, Object?>) {
      return _DartObjectKeyedDecoder(v, userInfo);
    }
    throw CodableException('Expected object for keyed(), found $v');
  }

  @override
  MappedDecoder mapped() {
    final v = _value;
    if (v is Map<String, Object?>) {
      return _DartObjectMappedDecoder(v, userInfo);
    }
    throw CodableException('Expected object for mapped(), found $v');
  }

  @override
  UnkeyedDecoder unkeyed() {
    final v = _value;
    if (v is List<Object?>) {
      return _DartObjectUnkeyedDecoder(v, userInfo);
    }
    throw CodableException('Expected array for unkeyed(), found $v');
  }

  @override
  SingleValueDecoder singleValue() =>
      _DartObjectSingleValueDecoder(_value, userInfo);

  @override
  Float64List? decodeUniformDoubleList(List<List<String>> propertyAliases) =>
      null;
}

final class _DartObjectMappedDecoder implements MappedDecoder {
  final Map<String, Object?> _map;
  final Map<Object, Object?> _userInfo;

  _DartObjectMappedDecoder(this._map, this._userInfo);

  @override
  bool containsKey(String key) => _map.containsKey(key);

  @override
  bool isNull(String key) => _map[key] == null;

  @override
  int readInt(String key) {
    final v = _map[key];
    if (v is int) return v;
    if (v is num) return v.toInt();
    throw CodableException('Expected int for $key, found $v');
  }

  @override
  int? readNullableInt(String key) => _map[key] == null ? null : readInt(key);

  @override
  double readDouble(String key) {
    final v = _map[key];
    if (v is num) return v.toDouble();
    throw CodableException('Expected double for $key, found $v');
  }

  @override
  double? readNullableDouble(String key) =>
      _map[key] == null ? null : readDouble(key);

  @override
  String readString(String key) {
    final v = _map[key];
    if (v is String) return v;
    throw CodableException('Expected String for $key, found $v');
  }

  @override
  String? readNullableString(String key) =>
      _map[key] == null ? null : readString(key);

  @override
  bool readBool(String key) {
    final v = _map[key];
    if (v is bool) return v;
    throw CodableException('Expected bool for $key, found $v');
  }

  @override
  bool? readNullableBool(String key) =>
      _map[key] == null ? null : readBool(key);

  @override
  Decoder nestedDecoder(String key) {
    final v = _map[key];
    if (v == null) {
      throw CodableException('Missing required key $key in mapped decoder');
    }
    return _DartObjectDecoder(v, userInfo: _userInfo);
  }

  @override
  T decodeKey<T>(String key, Decodable<T> decodable) {
    final v = _map[key];
    if (v == null) {
      throw CodableException('Missing required key $key in mapped decoder');
    }
    return decodable.decode(_DartObjectDecoder(v, userInfo: _userInfo));
  }

  @override
  T? decodeNullableKey<T>(String key, Decodable<T> decodable) {
    final v = _map[key];
    if (v == null) return null;
    return decodable.decode(_DartObjectDecoder(v, userInfo: _userInfo));
  }

  @override
  List<T> decodeListKey<T>(String key, Decodable<T> decodable) {
    final v = _map[key];
    if (v is List<Object?>) {
      return [
        for (final e in v)
          decodable.decode(_DartObjectDecoder(e, userInfo: _userInfo)),
      ];
    }
    throw CodableException('Expected list for $key, found $v');
  }

  @override
  List<int> decodeIntList(String key) {
    final v = _map[key];
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is int
              ? e
              : (e is num
                    ? e.toInt()
                    : throw CodableException(
                        'Expected int in list for $key, found $e',
                      )),
      ];
    }
    throw CodableException('Expected list for $key, found $v');
  }

  @override
  List<double> decodeDoubleList(String key) {
    final v = _map[key];
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is num
              ? e.toDouble()
              : throw CodableException(
                  'Expected double in list for $key, found $e',
                ),
      ];
    }
    throw CodableException('Expected list for $key, found $v');
  }

  @override
  Float64List decodeFloat64List(String key) =>
      Float64List.fromList(decodeDoubleList(key));

  @override
  List<String> decodeStringList(String key) {
    final v = _map[key];
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is String
              ? e
              : throw CodableException(
                  'Expected String in list for $key, found $e',
                ),
      ];
    }
    throw CodableException('Expected list for $key, found $v');
  }

  @override
  List<bool> decodeBoolList(String key) {
    final v = _map[key];
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is bool
              ? e
              : throw CodableException(
                  'Expected bool in list for $key, found $e',
                ),
      ];
    }
    throw CodableException('Expected list for $key, found $v');
  }
}

final class _DartObjectKeyedDecoder implements KeyedDecoder {
  final Map<String, Object?> _map;
  final Map<Object, Object?> _userInfo;
  late final List<String> _keys = _map.keys.toList(growable: false);
  int _index = 0;
  String? _activeKey;
  Object? _activeValue;
  bool _hasActive = false;

  _DartObjectKeyedDecoder(this._map, this._userInfo);

  @override
  bool moveNextKey() {
    if (_hasActive) return true;
    if (_index >= _keys.length) return false;
    final key = _keys[_index++];
    _activeKey = key;
    _activeValue = _map[key];
    _hasActive = true;
    return true;
  }

  Object? _consumeValue() {
    if (!moveNextKey()) {
      throw const CodableException('No more keys in object');
    }
    _hasActive = false;
    final v = _activeValue;
    _activeKey = null;
    _activeValue = null;
    return v;
  }

  @override
  String nextKey() {
    if (!moveNextKey()) {
      throw const CodableException('No more keys in object');
    }
    return _activeKey!;
  }

  @override
  String? peekKey() => moveNextKey() ? _activeKey : null;

  @override
  int selectKeyIndex(KeyOptions options) {
    if (!moveNextKey()) return -1;
    return options.indexOf(_activeKey!);
  }

  @override
  int selectStringIndex(KeyOptions options) => options.indexOf(readString());

  @override
  void skipValue() {
    if (!moveNextKey()) return;
    _consumeValue();
  }

  @override
  bool isNextNull() => moveNextKey() && _activeValue == null;

  @override
  void readNull() {
    final v = _consumeValue();
    if (v != null) {
      throw CodableException('Expected null, found $v');
    }
  }

  @override
  int readInt() {
    final v = _consumeValue();
    if (v is int) return v;
    if (v is num) return v.toInt();
    throw CodableException('Expected int, found $v');
  }

  @override
  int? readNullableInt() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readInt();
  }

  @override
  double readDouble() {
    final v = _consumeValue();
    if (v is num) return v.toDouble();
    throw CodableException('Expected double, found $v');
  }

  @override
  double? readNullableDouble() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readDouble();
  }

  @override
  String readString() {
    final v = _consumeValue();
    if (v is String) return v;
    throw CodableException('Expected String, found $v');
  }

  @override
  String? readNullableString() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readString();
  }

  @override
  (int start, int end) readStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree map');

  @override
  (int start, int end)? readNullableStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree map');

  @override
  bool readBool() {
    final v = _consumeValue();
    if (v is bool) return v;
    throw CodableException('Expected bool, found $v');
  }

  @override
  bool? readNullableBool() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readBool();
  }

  @override
  Decoder nestedDecoder() =>
      _DartObjectDecoder(_consumeValue(), userInfo: _userInfo);

  @override
  T decodeValue<T>(Decodable<T> decodable) => decodable.decode(
    _DartObjectDecoder(_consumeValue(), userInfo: _userInfo),
  );

  @override
  T? decodeNullableValue<T>(Decodable<T> decodable) {
    final v = _consumeValue();
    if (v == null) return null;
    return decodable.decode(_DartObjectDecoder(v, userInfo: _userInfo));
  }

  @override
  List<T> decodeList<T>(Decodable<T> decodable) {
    final v = _consumeValue();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          decodable.decode(_DartObjectDecoder(e, userInfo: _userInfo)),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  List<T>? decodeNullableList<T>(Decodable<T> decodable) {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return decodeList(decodable);
  }

  @override
  List<int> decodeIntList() {
    final v = _consumeValue();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is int
              ? e
              : (e is num
                    ? e.toInt()
                    : throw CodableException('Expected int in list, found $e')),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  List<double> decodeDoubleList() {
    final v = _consumeValue();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is num
              ? e.toDouble()
              : throw CodableException('Expected double in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  Float64List decodeFloat64List() => Float64List.fromList(decodeDoubleList());

  @override
  List<String> decodeStringList() {
    final v = _consumeValue();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is String
              ? e
              : throw CodableException('Expected String in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  List<bool> decodeBoolList() {
    final v = _consumeValue();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is bool
              ? e
              : throw CodableException('Expected bool in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }
}

final class _DartObjectUnkeyedDecoder implements UnkeyedDecoder {
  final List<Object?> _list;
  final Map<Object, Object?> _userInfo;
  int _index = 0;

  _DartObjectUnkeyedDecoder(this._list, this._userInfo);

  @override
  bool moveNext() => _index < _list.length;

  Object? _consumeElement() {
    if (_index >= _list.length) {
      throw const CodableException('No more elements in array');
    }
    return _list[_index++];
  }

  @override
  bool isNextNull() => _index < _list.length && _list[_index] == null;

  @override
  void readNull() {
    final v = _consumeElement();
    if (v != null) {
      throw CodableException('Expected null, found $v');
    }
  }

  @override
  int readInt() {
    final v = _consumeElement();
    if (v is int) return v;
    if (v is num) return v.toInt();
    throw CodableException('Expected int, found $v');
  }

  @override
  int? readNullableInt() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readInt();
  }

  @override
  double readDouble() {
    final v = _consumeElement();
    if (v is num) return v.toDouble();
    throw CodableException('Expected double, found $v');
  }

  @override
  double? readNullableDouble() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readDouble();
  }

  @override
  String readString() {
    final v = _consumeElement();
    if (v is String) return v;
    throw CodableException('Expected String, found $v');
  }

  @override
  String? readNullableString() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readString();
  }

  @override
  (int start, int end) readStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree list');

  @override
  (int start, int end)? readNullableStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree list');

  @override
  bool readBool() {
    final v = _consumeElement();
    if (v is bool) return v;
    throw CodableException('Expected bool, found $v');
  }

  @override
  bool? readNullableBool() {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return readBool();
  }

  @override
  void skipElement() {
    _consumeElement();
  }

  @override
  Decoder nestedDecoder() =>
      _DartObjectDecoder(_consumeElement(), userInfo: _userInfo);

  @override
  T decodeElement<T>(Decodable<T> decodable) => decodable.decode(
    _DartObjectDecoder(_consumeElement(), userInfo: _userInfo),
  );

  @override
  T? decodeNullableElement<T>(Decodable<T> decodable) {
    final v = _consumeElement();
    if (v == null) return null;
    return decodable.decode(_DartObjectDecoder(v, userInfo: _userInfo));
  }

  @override
  List<int> decodeIntList() {
    final v = _consumeElement();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is int
              ? e
              : (e is num
                    ? e.toInt()
                    : throw CodableException('Expected int in list, found $e')),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  List<double> decodeDoubleList() {
    final v = _consumeElement();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is num
              ? e.toDouble()
              : throw CodableException('Expected double in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  Float64List decodeFloat64List() => Float64List.fromList(decodeDoubleList());

  @override
  List<String> decodeStringList() {
    final v = _consumeElement();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is String
              ? e
              : throw CodableException('Expected String in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }

  @override
  List<bool> decodeBoolList() {
    final v = _consumeElement();
    if (v is List<Object?>) {
      return [
        for (final e in v)
          e is bool
              ? e
              : throw CodableException('Expected bool in list, found $e'),
      ];
    }
    throw CodableException('Expected List, found $v');
  }
}

final class _DartObjectSingleValueDecoder implements SingleValueDecoder {
  final Object? _value;
  final Map<Object, Object?> _userInfo;

  _DartObjectSingleValueDecoder(this._value, this._userInfo);

  @override
  bool isNull() => _value == null;

  @override
  void readNull() {
    if (_value != null) {
      throw CodableException('Expected null, found $_value');
    }
  }

  @override
  int readInt() {
    final v = _value;
    if (v is int) return v;
    if (v is num) return v.toInt();
    throw CodableException('Expected int, found $v');
  }

  @override
  int? readNullableInt() => _value == null ? null : readInt();

  @override
  double readDouble() {
    final v = _value;
    if (v is num) return v.toDouble();
    throw CodableException('Expected double, found $v');
  }

  @override
  double? readNullableDouble() => _value == null ? null : readDouble();

  @override
  String readString() {
    final v = _value;
    if (v is String) return v;
    throw CodableException('Expected String, found $v');
  }

  @override
  String? readNullableString() => _value == null ? null : readString();

  @override
  (int start, int end) readStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree value');

  @override
  (int start, int end)? readNullableStringSpan() =>
      throw UnsupportedError('String spans not supported on object-tree value');

  @override
  bool readBool() {
    final v = _value;
    if (v is bool) return v;
    throw CodableException('Expected bool, found $v');
  }

  @override
  bool? readNullableBool() => _value == null ? null : readBool();

  @override
  Decoder nestedDecoder() => _DartObjectDecoder(_value, userInfo: _userInfo);

  @override
  T decode<T>(Decodable<T> decodable) =>
      decodable.decode(_DartObjectDecoder(_value, userInfo: _userInfo));

  @override
  T? decodeNullable<T>(Decodable<T> decodable) =>
      isNull() ? null : decode(decodable);
}

final class _JsonCodableUnkeyedDecoder
    with _JsonPrimitiveDecoderMixin
    implements UnkeyedDecoder {
  @override
  final JsonTokenReader _reader;
  final JsonCodableDecoder _rootDecoder;
  bool _started = false;

  _JsonCodableUnkeyedDecoder(this._reader, this._rootDecoder);

  @override
  void _ensureStarted() {
    if (!_started) {
      _reader.beginArray();
      _started = true;
    }
  }

  @override
  bool moveNext() {
    _ensureStarted();
    final has = _reader.moveNext();
    if (!has) {
      _reader.endArray();
    }
    return has;
  }

  @override
  void skipElement() {
    _ensureStarted();
    _reader.skipValue();
  }

  @override
  Decoder nestedDecoder() => _rootDecoder;

  @override
  T decodeElement<T>(Decodable<T> decodable) => decodable.decode(_rootDecoder);

  @override
  T? decodeNullableElement<T>(Decodable<T> decodable) {
    if (isNextNull()) {
      readNull();
      return null;
    }
    return decodeElement(decodable);
  }

  @override
  List<int> decodeIntList() {
    _ensureStarted();
    final list = <int>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readInt());
    }
    _reader.endArray();
    return list;
  }

  @override
  List<double> decodeDoubleList() {
    _ensureStarted();
    final list = <double>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readDouble());
    }
    _reader.endArray();
    return list;
  }

  @override
  Float64List decodeFloat64List() {
    _ensureStarted();
    final list = <double>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readDouble());
    }
    _reader.endArray();
    return Float64List.fromList(list);
  }

  @override
  List<String> decodeStringList() {
    _ensureStarted();
    final list = <String>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readString());
    }
    _reader.endArray();
    return list;
  }

  @override
  List<bool> decodeBoolList() {
    _ensureStarted();
    final list = <bool>[];
    _reader.beginArray();
    while (_reader.moveNext()) {
      list.add(_reader.readBool());
    }
    _reader.endArray();
    return list;
  }
}

final class _JsonCodableSingleValueDecoder
    with _JsonPrimitiveDecoderMixin
    implements SingleValueDecoder {
  @override
  final JsonTokenReader _reader;
  final JsonCodableDecoder _rootDecoder;

  _JsonCodableSingleValueDecoder(this._reader, this._rootDecoder);

  @override
  void _ensureStarted() {}

  @override
  bool isNull() => isNextNull();

  @override
  Decoder nestedDecoder() => _rootDecoder;

  @override
  T decode<T>(Decodable<T> decodable) => decodable.decode(_rootDecoder);

  @override
  T? decodeNullable<T>(Decodable<T> decodable) =>
      isNull() ? null : decode(decodable);
}

/// Concrete high-performance streaming JSON encoder connecting
/// `package:codable` contracts directly to `JsonTokenWriter`.
final class JsonCodableEncoder implements Encoder {
  final JsonTokenWriter _writer;

  @override
  final Map<Object, Object?> userInfo;

  _JsonCodableKeyedEncoder? _activeKeyed;
  _JsonCodableUnkeyedEncoder? _activeUnkeyed;

  JsonCodableEncoder(this._writer, {this.userInfo = const {}});

  /// Encodes [value] to a newly allocated UTF-8 byte buffer using [encodable].
  static Uint8List toBytes<T>(
    T value,
    Encodable<T> encodable, {
    Map<Object, Object?> userInfo = const {},
    int? capacityHint,
  }) {
    final writer = AdaptiveJsonTokenWriter(capacityHint ?? 1024);
    final encoder = JsonCodableEncoder(writer, userInfo: userInfo);
    encodable.encode(value, encoder);
    encoder._finish();
    return writer.takeBytes();
  }

  /// Encodes [value] to a JSON String using [encodable].
  static String encode<T>(
    T value,
    Encodable<T> encodable, {
    Map<Object, Object?> userInfo = const {},
  }) {
    final bytes = toBytes(value, encodable, userInfo: userInfo);
    return utf8.decode(bytes);
  }

  /// Encodes [value] directly into [sink] using a chunked [JsonTokenWriter].
  static void toSink<T>(
    BytesBuilder sink,
    T value,
    Encodable<T> encodable, {
    Map<Object, Object?> userInfo = const {},
  }) {
    final writer = AdaptiveJsonTokenWriter.toSink(sink);
    final encoder = JsonCodableEncoder(writer, userInfo: userInfo);
    encodable.encode(value, encoder);
    encoder._finish();
    writer.flush();
  }

  /// Starts a chunked conversion that streams encoded UTF-8 byte chunks
  /// directly to [sink] via [JsonTokenWriter.toSink].
  static ChunkedConversionSink<T> startChunkedConversion<T>(
    Sink<List<int>> sink,
    Encodable<T> encodable, {
    Map<Object, Object?> userInfo = const {},
  }) {
    final byteSink = sink is ByteConversionSink
        ? sink
        : ByteConversionSink.from(sink);
    return _JsonCodableChunkedEncoderSink<T>(byteSink, encodable, userInfo);
  }

  void _finish() {
    _activeKeyed?._close();
    _activeKeyed = null;
    _activeUnkeyed?._close();
    _activeUnkeyed = null;
  }

  @override
  KeyedEncoder keyed({KeyOptions? options}) {
    _activeKeyed = _JsonCodableKeyedEncoder(this, _writer);
    return _activeKeyed!;
  }

  @override
  UnkeyedEncoder unkeyed() {
    _activeUnkeyed = _JsonCodableUnkeyedEncoder(this, _writer);
    return _activeUnkeyed!;
  }

  @override
  SingleValueEncoder singleValue() =>
      _JsonCodableSingleValueEncoder(this, _writer);
}

final class _JsonCodableKeyedEncoder implements KeyedEncoder {
  final JsonCodableEncoder _rootEncoder;
  final JsonTokenWriter _writer;
  bool _closed = false;

  _JsonCodableKeyedEncoder(this._rootEncoder, this._writer) {
    _writer.beginObject();
  }

  void _close() {
    if (!_closed) {
      _writer.endObject();
      _closed = true;
    }
  }

  @override
  void encodeInt(String key, int value) {
    _writer.writeName(key);
    _writer.writeInt(value);
  }

  @override
  void encodeNullableInt(String key, int? value) {
    if (value != null) {
      encodeInt(key, value);
    }
  }

  @override
  void encodeDouble(String key, double value) {
    _writer.writeName(key);
    _writer.writeDouble(value);
  }

  @override
  void encodeNullableDouble(String key, double? value) {
    if (value != null) {
      encodeDouble(key, value);
    }
  }

  @override
  void encodeString(String key, String value) {
    _writer.writeName(key);
    _writer.writeString(value);
  }

  @override
  void encodeNullableString(String key, String? value) {
    if (value != null) {
      encodeString(key, value);
    }
  }

  @override
  void encodeBool(String key, bool value) {
    _writer.writeName(key);
    _writer.writeBool(value);
  }

  @override
  void encodeNullableBool(String key, bool? value) {
    if (value != null) {
      encodeBool(key, value);
    }
  }

  @override
  void encodeNull(String key) {
    _writer.writeName(key);
    _writer.writeNull();
  }

  @override
  void encodeValue<T>(String key, T value, Encodable<T> encodable) {
    _writer.writeName(key);
    final child = JsonCodableEncoder(_writer, userInfo: _rootEncoder.userInfo);
    encodable.encode(value, child);
    child._finish();
  }

  @override
  void encodeNullableValue<T>(String key, T? value, Encodable<T> encodable) {
    if (value != null) {
      encodeValue(key, value, encodable);
    }
  }

  @override
  void encodeList<T>(String key, Iterable<T> elements, Encodable<T> encodable) {
    _writer.writeName(key);
    _writer.beginArray();
    for (final e in elements) {
      final child = JsonCodableEncoder(
        _writer,
        userInfo: _rootEncoder.userInfo,
      );
      encodable.encode(e, child);
      child._finish();
    }
    _writer.endArray();
  }

  @override
  void encodeIntList(String key, List<int> values) {
    _writer.writeName(key);
    _writer.beginArray();
    for (final v in values) {
      _writer.writeInt(v);
    }
    _writer.endArray();
  }

  @override
  void encodeDoubleList(String key, List<double> values) {
    _writer.writeName(key);
    _writer.beginArray();
    for (final v in values) {
      _writer.writeDouble(v);
    }
    _writer.endArray();
  }

  @override
  void encodeStringList(String key, List<String> values) {
    _writer.writeName(key);
    _writer.beginArray();
    for (final v in values) {
      _writer.writeString(v);
    }
    _writer.endArray();
  }

  @override
  void encodeBoolList(String key, List<bool> values) {
    _writer.writeName(key);
    _writer.beginArray();
    for (final v in values) {
      _writer.writeBool(v);
    }
    _writer.endArray();
  }
}

final class _JsonCodableUnkeyedEncoder implements UnkeyedEncoder {
  final JsonCodableEncoder _rootEncoder;
  final JsonTokenWriter _writer;
  bool _closed = false;

  _JsonCodableUnkeyedEncoder(this._rootEncoder, this._writer) {
    _writer.beginArray();
  }

  void _close() {
    if (!_closed) {
      _writer.endArray();
      _closed = true;
    }
  }

  @override
  void encodeInt(int value) => _writer.writeInt(value);

  @override
  void encodeNullableInt(int? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeInt(value);
    }
  }

  @override
  void encodeDouble(double value) => _writer.writeDouble(value);

  @override
  void encodeNullableDouble(double? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeDouble(value);
    }
  }

  @override
  void encodeString(String value) => _writer.writeString(value);

  @override
  void encodeNullableString(String? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeString(value);
    }
  }

  @override
  void encodeBool(bool value) => _writer.writeBool(value);

  @override
  void encodeNullableBool(bool? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeBool(value);
    }
  }

  @override
  void encodeNull() => _writer.writeNull();

  @override
  void encodeElement<T>(T value, Encodable<T> encodable) {
    final child = JsonCodableEncoder(_writer, userInfo: _rootEncoder.userInfo);
    encodable.encode(value, child);
    child._finish();
  }

  @override
  void encodeNullableElement<T>(T? value, Encodable<T> encodable) {
    if (value == null) {
      _writer.writeNull();
    } else {
      encodeElement(value, encodable);
    }
  }

  @override
  void encodeList<T>(Iterable<T> elements, Encodable<T> encodable) {
    for (final e in elements) {
      encodeElement(e, encodable);
    }
  }
}

final class _JsonCodableSingleValueEncoder implements SingleValueEncoder {
  final JsonCodableEncoder _rootEncoder;
  final JsonTokenWriter _writer;

  _JsonCodableSingleValueEncoder(this._rootEncoder, this._writer);

  @override
  void encodeInt(int value) => _writer.writeInt(value);

  @override
  void encodeNullableInt(int? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeInt(value);
    }
  }

  @override
  void encodeDouble(double value) => _writer.writeDouble(value);

  @override
  void encodeNullableDouble(double? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeDouble(value);
    }
  }

  @override
  void encodeString(String value) => _writer.writeString(value);

  @override
  void encodeNullableString(String? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeString(value);
    }
  }

  @override
  void encodeBool(bool value) => _writer.writeBool(value);

  @override
  void encodeNullableBool(bool? value) {
    if (value == null) {
      _writer.writeNull();
    } else {
      _writer.writeBool(value);
    }
  }

  @override
  void encodeNull() => _writer.writeNull();

  @override
  void encode<T>(T value, Encodable<T> encodable) {
    final child = JsonCodableEncoder(_writer, userInfo: _rootEncoder.userInfo);
    encodable.encode(value, child);
    child._finish();
  }

  @override
  void encodeNullable<T>(T? value, Encodable<T> encodable) {
    if (value == null) {
      _writer.writeNull();
    } else {
      final child = JsonCodableEncoder(
        _writer,
        userInfo: _rootEncoder.userInfo,
      );
      encodable.encode(value, child);
      child._finish();
    }
  }
}

final class _JsonCodableChunkedDecoderSink<T> extends ByteConversionSinkBase {
  final Sink<T> _sink;
  final Decodable<T> _decodable;
  final Map<Object, Object?> _userInfo;
  final ScratchByteAccumulator _accumulator = ScratchByteAccumulator();
  bool _isClosed = false;

  _JsonCodableChunkedDecoderSink(this._sink, this._decodable, this._userInfo);

  @override
  void add(List<int> chunk) {
    if (_isClosed) {
      throw StateError('Cannot add to a closed sink');
    }
    _accumulator.add(chunk);
  }

  @override
  void addSlice(List<int> chunk, int start, int end, bool isLast) {
    if (_isClosed) {
      throw StateError('Cannot addSlice to a closed sink');
    }
    RangeError.checkValidRange(start, end, chunk.length);
    if (start < end) {
      _accumulator.addSlice(chunk, start, end);
    }
    if (isLast) {
      close();
    }
  }

  @override
  void close() {
    if (_isClosed) return;
    _isClosed = true;
    final bytes = _accumulator.takeBytes();
    final decoder = JsonCodableDecoder.fromBytes(bytes, userInfo: _userInfo);
    try {
      _sink.add(_decodable.decode(decoder));
    } finally {
      _accumulator.release(canPool: !decoder._payloadEscaped);
    }
    _sink.close();
  }
}

final class _ByteSinkAdapter implements BytesBuilder {
  final ByteConversionSink _byteSink;
  int _length = 0;

  _ByteSinkAdapter(this._byteSink);

  @override
  void add(List<int> bytes) {
    _length += bytes.length;
    _byteSink.add(bytes);
  }

  @override
  void addByte(int byte) {
    _length += 1;
    _byteSink.add([byte]);
  }

  @override
  void clear() {
    _length = 0;
  }

  @override
  bool get isEmpty => _length == 0;

  @override
  bool get isNotEmpty => _length > 0;

  @override
  int get length => _length;

  @override
  Uint8List takeBytes() => throw UnsupportedError('Not supported on adapter');

  @override
  Uint8List toBytes() => throw UnsupportedError('Not supported on adapter');
}

final class _JsonCodableChunkedEncoderSink<T>
    implements ChunkedConversionSink<T> {
  final ByteConversionSink _byteSink;
  final Encodable<T> _encodable;
  final Map<Object, Object?> _userInfo;
  bool _isClosed = false;

  _JsonCodableChunkedEncoderSink(
    this._byteSink,
    this._encodable,
    this._userInfo,
  );

  @override
  void add(T value) {
    if (_isClosed) {
      throw StateError('Cannot add to a closed sink');
    }
    final writer = AdaptiveJsonTokenWriter.toSink(_ByteSinkAdapter(_byteSink));
    final encoder = JsonCodableEncoder(writer, userInfo: _userInfo);
    _encodable.encode(value, encoder);
    encoder._finish();
    writer.flush();
  }

  @override
  void close() {
    if (_isClosed) return;
    _isClosed = true;
    _byteSink.close();
  }
}
