targets:
  $default:
    sources:
      - "lib/**"
      - "benchmark/**"
      - "test/**"
      - "$package$"
    builders:
      codable_generator|codable:
        generate_for:
          - "benchmark/**"
          - "test/**"
