name: codable_benchmarks
description: End-to-end performance and cross-language serialization benchmarks for package:codable.
version: 0.1.0-dev
publish_to: none

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  bench_press: ^0.3.0
  codable: ^0.1.0-dev
  json_annotation: ^4.9.0

dev_dependencies:
  analyzer: any
  args: ^2.4.0
  build_runner: ^2.4.14
  checks: ^0.3.0
  codable_builder: ^0.1.0-dev
  dart_flutter_team_lints: ^3.0.0
  http: ^1.1.0
  json_serializable: ^6.9.0
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_static: ^1.1.0
  source_gen: any
  source_maps: ^0.10.0
  source_span: ^1.10.0
  test: ^1.25.8
  vm_service: ^15.3.0
  webkit_inspection_protocol: ^1.2.0
