name: codable_benchmarks
description: End-to-end performance and cross-language serialization benchmarks for package:codable.
version: 0.1.0-dev
publish_to: none

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  bench_press:
    git:
      url: https://github.com/kevmoo/bench_press.git
      ref: 2c9e8315673d72c2c9a9c4e6ac0de772f8d53a7e
  codable: ^0.1.0-dev
  json_annotation: ^4.9.0

dev_dependencies:
  analyzer: any
  build_runner: ^2.4.14
  checks: ^0.3.0
  codable_builder: ^0.1.0-dev
  dart_flutter_team_lints: ^3.0.0
  json_serializable: ^6.9.0
  source_gen: any
  test: ^1.25.8
