targets:
  $default:
    sources:
      - "lib/**"
      - "example/**"
      - "test/**"
      - "$package$"
    builders:
      codable_builder|codable:
        generate_for:
          - "example/**"
          - "test/**"
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - lines_longer_than_80_chars
            - unnecessary_lambdas
            - deprecated_member_use
            - unused_element
