name: Dart CI

on:
  push:
    branches: [ main, sdk-integration, 'feat/**' ]
  pull_request:
    branches: [ main, sdk-integration ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk: [stable, beta, dev]

    steps:
      - uses: actions/checkout@v7

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Swap to mock substrate for CI
        run: dart run tool/switch_substrate.dart mock

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test pkgs/codable pkgs/codable_builder pkgs/codable_benchmarks
